### ISSUE TITLE
Handle shell appropriately without errorneous "rm /bin/sh && ln -s /bin/bash /bin/sh"

### ISSUE THREAD

**Issue by Voronenko** [DataDog/datadog-agent-buildimages#64]
it is quite unusual to see workarounds like 

```sh
rm /bin/sh && ln -s /bin/bash /bin/sh
```

https://github.com/DataDog/datadog-agent-buildimages/blame/master/deb-x64/Dockerfile#L2

Most likely, what you are looking for is wrapping conda install into  /bin/bash -c "commands"

```Dockerfile

# Update pip, setuptools and misc deps
RUN /bin/bash -c "source /root/.bashrc && conda activate ddpy2 \
    && pip install -i https://pypi.python.org/simple pip==${DD_PIP_VERSION} \
    && pip install --ignore-installed setuptools==${DD_SETUPTOOLS_VERSION} \
    && pip install invoke distro==1.4.0 awscli==1.16.240"

# Update pip, setuptools and misc deps
RUN /bin/bash -c  "source /root/.bashrc && conda activate ddpy3 \
    && pip install -i https://pypi.python.org/simple pip==${DD_PIP_VERSION} \
    && pip install --ignore-installed setuptools==${DD_SETUPTOOLS_VERSION} \
    && pip install invoke distro==1.4.0 awscli==1.16.240"
```

**Comment by Voronenko** [comment]
https://github.com/DataDog/datadog-agent-buildimages/pull/65

**Comment by mx-psi** [comment]
Hi @Voronenko, thanks for your contribution! The PR looks good to me, I think we could get rid of the `bash` calls altogether and use the [`SHELL` command](https://docs.docker.com/engine/reference/builder/#shell) to set the default shell. What do you think? We can handle that ourselves on a future PR otherwise.
